name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js latest 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Execute unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo 'mavramov'

  run_ui_tests:

    needs: run-unit-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js latest 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install   
    - name: Start the app in background
      run: npm run start &
    - name: Execute UI tests
      run: npm run test:ui

  render_deploy:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: run_ui_tests

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true